### ISSUE TITLE
Have 16 2d panels instead of 1

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#11]
In order for Ian to be able to write some use cases, we need to have 16 copies of the 2d panel

**Comment by tbenz9** [comment]
isn't this what we've been planning all along with the cover-flow idea?

**Comment by spuder** [comment]
Yes, I just made a ticket for it because that is what i am working on next. I think we need to rewrite the 2d panel because it just isn't designed to scale. Modifying it to make 16 would be super difficult. We can reuse a lot of the same logic.

**Comment by tbenz9** [comment]
ok, I don't think I can work on it tomorrow (Monday), but perhaps Tuesday.
