### ISSUE TITLE
Save to Tree map instead of hashmap

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#12]
Tree maps are just like hash maps except they are sorted by the key on insert. That way we get a numerical list instead of a list the order the leds were clicked.

**Comment by tbenz9** [comment]
Is this still an issue, I kinda thought we decided this wasn't going to work, and we want to implement the object oriented model instead.

**Comment by spuder** [comment]
If we are saving to a csv file then the tree map lists the leds in order of number instead of order they were clicked. This won't be needed once json is implemented

**Comment by spuder** [comment]
Parent class will be handling internal data structures from now on.
