### ISSUE TITLE
Cubes with odd number of rows/columns/curtins wrap incorrectly in 2d view

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#17]
You can not have a cube with odd values (9x9x9 or 5x5x5) since they wrap incorrectly

**Comment by tbenz9** [comment]
I'll look into using mod(cubeSize) because i think that would fix our problem.

**Comment by spuder** [comment]
Ok, I put this as release 1.0 in 2 months since right now all we need is a 16 / 16. The current led size works great. 

The priority is low.
