### ISSUE TITLE
Cube_Of_Spheres - Occasionally Leds will not unselect 

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#2]
In some circumstances selecting a led, then unselecting it will leave the led shown as selected.

**Comment by tbenz9** [comment]
I found a big tip on this problem.  If you click somewhere in the black (not on an LED) and then hover over an LED it will select it but I don't think it's changing the ledHasBeenClicked variable.

**Comment by spuder** [comment]
Added if statement to mouse Pressed method. The only led that works as expected is 0 0 0

**Comment by spuder** [comment]
Led is being hovered over
Led is being hovered over
Led is being hovered over
ledIsHoveredOver is : 16 16 16: true
Led is being hovered over
Led has been clicked
Clicked LED 15 15 15
Led is being hovered over
Led is being hovered over
Led is being hovered over
Led is being hovered over
Led is being hovered over

**Comment by spuder** [comment]
Apparently the mouse press is waiting until the end of the loop before it is executed. Does it need a new thread?

Led 14 0 14: is being hovered over
Led 14 0 14: is being hovered over
Led 14 0 14: is being hovered over
Mouse was pressed durring 15 15 15: 
Led 14 0 14: is being hovered over
Led 14 0 14: is being hovered over
Led 14 0 14: is being hovered over
Led 14 0 14: is being hovered over

**Comment by tbenz9** [comment]
We added an additional else if statement that checks if the hashmap value is false and turns off the LED if it is false.
