### ISSUE TITLE
Hover over led changes its color to highlighted

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#21]
Dragging your mouse over the 2d pane highlights the leds as they hovered over.

**Comment by tbenz9** [comment]
I don't think this is worth our time or effort right now, also, having a hover color that is different than the LED color might get confusing once we implement colors in the LED program.

**Comment by spuder** [comment]
This is for the beta release after vmware world. The purpose of a hover color would be to give visual feedback of where you are about to click. I envision it being very subtile such as changing the unlight led from dark grey to a slightly lighter dark grey, or adding a slight shadow to the led though stroke(). 

There is no way to set priority but if there was this would be the lowest of the low. Something nice for a future release.

**Comment by spuder** [comment]
See processing example > Input > MouseFunctions
