### ISSUE TITLE
Convert csv file to JSON

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#24]

**Comment by tbenz9** [comment]
I'm voting this up, because we'd be able to fit an entire animation on a single file, instead of a mass of files.

**Comment by spuder** [comment]
I agree that this is the best way to do it. I am concerned about time. The panel class and cube class aren't yet written which is a big part of our json hierarchy isn't it?

**Comment by spuder** [comment]
Ive been looking into this and can't find a lot of examples. Here is one 
https://github.com/agoransson/JSON-processing/tree/master/examples/reading_yahoo_weather
This is going to take a lot more research

**Comment by spuder** [comment]
This is to be part of the php cube. The format we are currently using is for adaptives cube only. The php cube should have the option to export to multlple formatted csv's. One of which could be json
