### ISSUE TITLE
3d Restore led color from file

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#29]
The final decision on the csv layout needs to be decided. I don't think there is enough time to implement json for the alpha release. Ian needs to start editing asap. 

Csv gives us the option to fall back to excel if something catastrophic were to happen. 

Version 1.0 should use JSON

**Comment by spuder** [comment]
I think this one is pretty much done. We need to modify the format that we are saving / exporting from

**Comment by tbenz9** [comment]
This has been done
