### ISSUE TITLE
3d Change led color rgb not just on off

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#30]
Pressing 1 on the keyboard sets the color mode to red. All subsequent leds clicked on are then set to red
Pressing 2 on the keyboard sets the color mode to green......

**Comment by tbenz9** [comment]
This has been implemented, but instead of hitting 1-7 you just hit the first letter of the color.  i.e. "r" turns it red, "b" turns it blue, etc.  For Red, Green, Blue, Yellow, White, Purple, Orange.  You can also export and import the files with colors.

**Comment by spuder** [comment]
Excellent. Can you push the changes so I can see it?
