### ISSUE TITLE
3d Pressing i causes app to hang

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#33]
Steps to reproduce:

Open cube of spheres. 

press the i key on keyboard. 

Program becomes un responsive. Will no longer allow clicking of leds, pressing shift to rotate or any other interaction. 

Pressing I should open a text box to prompt what file to import.

**Comment by tbenz9** [comment]
Thats weird, I had it working fine on Saturday, import and all, I'll be curious to see if it works on my desktop at Adaptive.

**Comment by spuder** [comment]
It could be the fact that I am on a mac. But I doubt it.

**Comment by tbenz9** [comment]
It could also be related to slightly different versions of java/Processing?

**Comment by spuder** [comment]
Could be, I arm running the custom apple jre 1.6.0.33 and processing 1.5.1. 

I'd like to switch everything to processing 2.0 but there are some issues with screen.with and window with. Perhaps all spark cube 2.0 will be written in processing 2.0

**Comment by tbenz9** [comment]
Does not happen on my Desktop, changing priority to low.

**Comment by spuder** [comment]
I discovered the reason is because of threading. The open file prompt should be encapsulated in a new thread. 

  //Open dialog prompt
  new Thread(
  new Runnable() 
  {
    public void run()
    {
      openFile(selectInput());
    }
  }
  ).start();
