### ISSUE TITLE
2d Click led second time to set color back to grey

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#34]
You can turn an led on, but you can't turn it off.

**Comment by tbenz9** [comment]
is this the 2d or 3d, On the 3d I think you can turn it off.

**Comment by spuder** [comment]
the 2d. I got color working but you can't turn it off. I'll get that figured out tomorrow.

**Comment by tbenz9** [comment]
I created a extra color called "off" that just turns the LED off.
