### ISSUE TITLE
2d Change led color rgb not just on off

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#4]
Through either a button or keyboard shortcut, save the current desired color. All LEDs selected highlight to the desired color

**Comment by tbenz9** [comment]
Ian requested 7 colors, you can find them listed on the Wiki.  You can also look at the Cube_Of_Spheres code for the RGB values I picked.

**Comment by spuder** [comment]
now allows for multiple colors. Separate ticket for the full color spectrum & turn leds off.
