### ISSUE TITLE
2d & 3d Convert integers to hex Strings

### ISSUE THREAD

**Issue by spuder** [spuder/All-Spark-Cube#40]
We can get human readable hex with the following

String aString = "#" + Integer.toHexString(intColor).substring(2);

The subString(2)  gives us a 6 digit hex instead of 8 digit

We could also use Color.decode and Color.encode

FYI 

Color is actually a Java class not a processing class

javalobby.org/java/forums/t19183.html

**Comment by tbenz9** [comment]
I'm still confused why we even need human readable, I don't ever plan to read it...
