### ISSUE TITLE
Saved file includes blank frames

### ISSUE THREAD

**Issue by iannate** [spuder/All-Spark-Cube#47]
When you save a file and it has extra blank frames on the end, it saves those blank frames. It would be nice to have either a way to delete extra frames on the end, or when you save the file it ignores the blank frames at the end.

**Comment by spuder** [comment]
This is a good idea, I am also thinking that users will be less likely to make blank frames if you had to push 'shift' left/right or some other modifier key to create a new frame, while left/right only navigates between them.
