### ISSUE TITLE
File Export doesn't work

### ISSUE THREAD

**Issue by iannate** [spuder/All-Spark-Cube#62]
The new version of the software will pull in files fine (in the old 4096 per frame format), but the file export does not work. The dialogue pops up fine, but it doesn't actually save the file off in any format.

**Comment by spuder** [comment]
I'll look at this. We put a new commit to github friday at 5pm. Make sure you do a git pull on the directory to get the latest updates.

**Comment by iannate** [comment]
I pulled the new code earlier today, so I'm all up to date.
 Thanks,
Ian

**Comment by tbenz9** [comment]
I just got off the phone with Ian, it appears to be a bug when you import from the old format it won't export to the new format.  This is perhaps caused by changes Spencer made in the different classes.  The work around is to only work in the new format, i.e. Ian has to re-make his animations.

**Comment by tbenz9** [comment]
If you start a new animation the export works fine.

**Comment by spuder** [comment]
@iannate  Keep the existing files intact, Once I get the import working, it would be pretty easy to edit them in excel to the new format and then import them.
